### PR TITLE
Add glFinish() before unmapping the surface

### PR DESCRIPTION
**Pull request by 9000h**
cherry picked from rellla
https://github.com/rellla/softhddevice-openglosd/commit/22590848da82f0d33c816ed65261207b46cd6312

### CODE REVIEW

**Comment by jojo61** [comment]
With this patch the OSD crashes when switching to UHD. I need to reverse it. Could you tell me why you think it s needed ?

**Comment by 9000h** [comment]
sorry did not test it with UHD

**Comment by jojo61** [comment]
I will investigate why it crashes with UHD. Maybe a timing issue that needs locking.

**Comment by 9000h** [comment]
if I get it right glFinish will block until all gl stuff is done, and glFlush will not

**Pull request merged**
